### PR TITLE
Add: first version of INSTALL.md

### PR DESCRIPTION
**Pull request by nichtsfrei**
To describe how to install, configure and run Notus add a INSTALL.md

### CODE REVIEW

**Comment by bjoernricks** [comment]
Could we integrate that directly into the README? the README has already an install section.

**Comment by ArnoStiefvater** [comment]
gvm-libs, gvmd, openvas-scanner all have an Install.md so I thought would be good to have it uniform.

**Comment by nichtsfrei** [comment]
I also think it should be separated; besides the conformable point of Arno in the INSTALL.md we can be more descriptive if we choose to later on without having one huge document.

**Comment by bjoernricks** [comment]
> gvm-libs, gvmd, openvas-scanner all have an Install.md so I thought would be good to have it uniform.

personally I never liked that and it was a relict from the pre-git/github era. But it is at least linked in the README now.

**Pull request merged**
